### ISSUE TITLE
for snapshot versions, replace '-SNAPSHOT' with timestamp '.{yyyymmddhhmmss}'

### ISSUE THREAD

**Issue by missedone** [testng-team/testng-p2#10]
for snapshot versions, it's better to replace '-SNAPSHOT' with timestamp '.{yyyymmddhhmmss}' so that when the actual snapshot updated, the user can use the new build otherwise, user won't see the update.

the behavior will be similar as what Maven Tycho plugin did, update the version in MANIFEST.MF, and appends to bundle file name

**Comment by mschreiber** [comment]
Not sure if my last commit is what we want. Strange is, that the feature version is still using some hash but the testng plugin does use the timestamp qualifier...

**Comment by missedone** [comment]
for released version (e.g. 6.9.12), that's good, i don't mind the hashing suffix of the feature jar as long as the feature.xml is correct. but yes, that's weird.
I think when dealing with the snapshot version (replacing snapshot with qualifier timestamp), we will learn more about that then.

**Comment by missedone** [comment]
with help of https://github.com/stempler/bnd-platform/issues/20, commit https://github.com/testng-team/testng-p2/commit/444b7009d47033d00f74cdf282a24a4ba010f534, the output now looks quite good:

```
ll build/updatesite/*
-rw-r--r-- 1 nick staff  960 Oct 21 07:14 build/updatesite/artifacts.jar
-rw-r--r-- 1 nick staff 2.1K Oct 21 07:14 build/updatesite/content.jar

build/updatesite/features:
total 4.0K
-rw-r--r-- 1 nick staff 412 Oct 21 07:14 org.testng.p2.feature_6.9.13.20161021141424.jar

build/updatesite/plugins:
total 2.1M
-rw-r--r-- 1 nick staff  55K Oct 21 07:14 com.beust.jcommander.source_1.48.0.jar
-rw-r--r-- 1 nick staff  63K Oct 21 07:14 com.beust.jcommander_1.48.0.jar
-rw-r--r-- 1 nick staff 296K Oct 21 07:14 org.apache-extras.beanshell.bsh.source_2.0.0.b6.jar
-rw-r--r-- 1 nick staff 385K Oct 21 07:14 org.apache-extras.beanshell.bsh_2.0.0.b6.jar
-rw-r--r-- 1 nick staff 476K Oct 21 07:14 org.testng.source_6.9.13.20161021141424.jar
-rw-r--r-- 1 nick staff 840K Oct 21 07:14 org.testng_6.9.13.20161021141424.jar
```
