### ISSUE TITLE
Forbidden: https://dl.bintray.com/testng-team/testng-eclipse-release/7.3.0

### ISSUE THREAD

**Issue by cmunier** [testng-team/testng-p2#35]
Hi there,

the P2 Repository on Bintray for TestNG 7.3.0 ist noch reachable: https://dl.bintray.com/testng-team/testng-eclipse-release/7.3.0 
(HTTP Forbidden)

Thanks in advance,
Christian

**Comment by missedone** [comment]
@cmunier , thanks for reporting, due to the bintray sunset, we have to move the new update site at https://testng.org/testng-p2-update-site
the source: https://github.com/testng-team/testng-p2-update-site

let me update readme as well
