### ISSUE TITLE
org.testng.eclipse.maven.feature missing in P2 repository

### ISSUE THREAD

**Issue by cmunier** [testng-team/testng-p2#37]
Hi there,

previously I installed org.testng.eclipse.maven.feature 7.3.0.202008060412 from https://dl.bintray.com/testng-team/testng-eclipse-release/7.3.0.

With https://dl.bintray.com/testng-team/testng-eclipse-release/7.3.0, this feature is now missing.

Is the m2e integration no longer available?

Thanks & kind regards,
Christian

**Comment by missedone** [comment]
@cmunier , yes, the testng maven integration is available in separate update site repo: https://github.com/testng-team/testng-eclipse-update-site

this repo is for the osgifiled testng core (aka, testng p2) only
