### ISSUE TITLE
Not able to install TestNG from Marketpalce

### ISSUE THREAD

**Issue by nvnetmt** [testng-team/testng-p2#38]
Hi,

Tried installign TestNG from market place (https://testng.org/testing-eclipse-update-site). its not happening and giving forbiddeen error. 

Can someone help on this?

Its quite urgent.. 

Thanks
Nvn

**Comment by juherr** [comment]
It will work with the good url: https://testng.org/testng-eclipse-update-site/

**Comment by nvnetmt** [comment]
I tried, Its opening. But If I take any url from that and try to navigate get the 404 error. Attached screenshot. And how can i bypass the URl in Eclipse marketpalce. 
![image](https://user-images.githubusercontent.com/86566799/123555364-f204b280-d7a2-11eb-8272-50d230c4a650.png)

**Comment by nvnetmt** [comment]
Tried installign the New Software option. Getting below error as well. 

![image](https://user-images.githubusercontent.com/86566799/123555601-56744180-d7a4-11eb-8e47-7955b3d84f35.png)

**Comment by juherr** [comment]
Everything looks good:

1. You are not supposed to browse files with a browser: that's why you see the 404 error.
2. Eclipse is reading the URL well as it found the expected version: `7.4.0.xxxx`.

What is exactly your error?

**Comment by missedone** [comment]
@nvnetmt , pls share the detail of the error.
also, to speedup the installation, you can uncheck the option "Contact all update sites during install to find required software"

**Comment by missedone** [comment]
besides, looks like you don't use Maven in your project, so don't install "TestNG M2E (Maven) Integration" plugin

**Comment by nvnetmt** [comment]
Thanks its able to install. Thank you so much..
